### ISSUE TITLE
"A mongo field must be a part of the Contains method." when querying using Id property

### ISSUE THREAD

**Issue by Kostassoid** [craiggwilson/fluent-mongo#40]
When querying something like:

```
experts.Where(e => authorsIds.Contains(e.Id)).ToList()
```

where experts is a fluent-mongo Queryable collection and authorsIds is just some List<Guid>.

Id is declared as

```
public Guid Id { get; protected set; }
```

I'm getting:

FluentMongo.Linq.InvalidQueryException : A mongo field must be a part of the Contains method.
at FluentMongo.Linq.Translators.BsonDocumentFormatter.VisitMethodCall(MethodCallExpression m) in D:\Projects\ExternalLibs\fluent-mongo\src\FluentMongo\Linq\Translators\BsonDocumentFormatter.cs: line 196
at FluentMongo.Linq.Expressions.ExpressionVisitor.Visit(Expression exp) in D:\Projects\ExternalLibs\fluent-mongo\src\FluentMongo\Linq\Expressions\ExpressionVisitor.cs: line 62
at FluentMongo.Linq.Translators.MongoQueryObjectBuilder.VisitSelect(SelectExpression select) in D:\Projects\ExternalLibs\fluent-mongo\src\FluentMongo\Linq\Translators\MongoQueryObjectBuilder.cs: line 81
at FluentMongo.Linq.Translators.MongoQueryObjectBuilder.VisitProjection(ProjectionExpression projection) in D:\Projects\ExternalLibs\fluent-mongo\src\FluentMongo\Linq\Translators\MongoQueryObjectBuilder.cs: line 87
at FluentMongo.Linq.Translators.MongoQueryObjectBuilder.Build(Expression expression) in D:\Projects\ExternalLibs\fluent-mongo\src\FluentMongo\Linq\Translators\MongoQueryObjectBuilder.cs: line 19
at FluentMongo.Linq.ExecutionBuilder.VisitProjection(ProjectionExpression projection) in D:\Projects\ExternalLibs\fluent-mongo\src\FluentMongo\Linq\ExecutionBuilder.cs: line 21
at FluentMongo.Linq.MongoQueryProvider.Execute(Expression expression) in D:\Projects\ExternalLibs\fluent-mongo\src\FluentMongo\Linq\MongoQueryProvider.cs: line 98
at FluentMongo.Linq.MongoQuery`1.GetEnumerator() in D:\Projects\ExternalLibs\fluent-mongo\src\FluentMongo\Linq\MongoQuery.cs: line 102
at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
at System.Linq.Enumerable.ToList(IEnumerable`1 source)
....

**Comment by Kostassoid** [comment]
Update: authorsIds in example above was a List of Nullable Guids! when changed to simple Guids everything worked fine. Don't know if it's an issue anymore.

**Comment by craiggwilson** [comment]
Sounds like we aren't handling nullable types very well.
